### ISSUE TITLE
User systemd service for home-manager

### ISSUE THREAD

**Issue by mightyiam** [nicolas-goudry/earth-view#5]
Please

**Comment by nicolas-goudry** [comment]
The modules are already using a systemd user-managed service, could you please be more specific as to what you want/need?

**Comment by mightyiam** [comment]
I remember the readme said otherwise. Did I misunderstand?

**Comment by nicolas-goudry** [comment]
You are right, this has been changed in v1.4.0:

- [CHANGELOG](https://github.com/nicolas-goudry/earth-view/blob/master/CHANGELOG.md#v140---27042024)
- [README](https://github.com/nicolas-goudry/earth-view?tab=readme-ov-file#systemd)
- [Source](https://github.com/nicolas-goudry/earth-view/blob/master/modules/nixos/default.nix#L115)

**Comment by nicolas-goudry** [comment]
Closing this now. Feel free to reopen or fill a new issue if needed.
